version: "3.8"
services:
  postgres:
    image: postgres:17.2-alpine
    restart: unless-stopped
    networks:
      - story-telling
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    name: story-telling-database

networks:
  story-telling: